-- Generated by nwg-displays on 2026-06-14 at 14:04:57. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@165.0",
    position = "2387x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1600x900@59.98",
    position = "4307x0",
    scale = 1.0,
    transform = 3
})
